[theme]
base = "dark"

# General color setup
textColor = "#e2e8f0"
primaryColor = "#615fff"
backgroundColor = "#1d293d"
secondaryBackgroundColor = "#0f172b"

# Widgets
showWidgetBorder = true
borderColor = "#314158"

# Dataframes
dataframeHeaderBackgroundColor = "#1d293d"

# Base text
font = "IBM Plex Sans"
baseFontWeight = 300
baseFontSize = 17

# Heading text
headingFont = "IBM Plex Sans"
headingFontWeights = [300, 400, 400, 300, 300, 300]
headingFontSizes = ["2.5rem", "1.5rem", "1rem"]

[[theme.fontFaces]]
family = "IBM Plex Sans"
style = "normal"
weight = "300 700"
url = "https://fonts.gstatic.com/s/ibmplexsans/v14/zYX-KVElMYYaJe8bpLHnCw.woff2"